
//PROGRAMACION -------------------------------------

GET http://localhost:3000/api/cursos/programacion

###

GET http://localhost:3000/api/cursos/programacion/python

###

GET http://localhost:3000/api/cursos/programacion/python/basico

###

POST http://localhost:3000/api/cursos/programacion HTTP/1.1
Content-Type: application/json

{
    "id": 4,
    "titulo" : "Aprende Node.js" ,
    "lenguaje" : "javascript" ,
    "vistas" : 45676,
    "nivel" : "basico"
}

###

PUT http://localhost:3000/api/cursos/programacion/2 HTTP/1.1
Content-Type: application/json

{
    "id": 2,
    "titulo": "Python intermedio con proyectos" ,
    "lenguaje" : "python",
    "vistas": 123996,
    "nivel": "intermedio"
}

###

PATCH http://localhost:3000/api/cursos/programacion/2 HTTP/1.1
Content-Type: application/json

{
    "vistas": 123996
}

###

DELETE http://localhost:3000/api/cursos/programacion/2

//MATEMATICAS --------------------------------------------------------------

###

GET http://localhost:3000/api/cursos/matematicas

###

POST http://localhost:3000/api/cursos/matematicas HTTP/1.1
Content-Type: application/json

{
    "id": 3,
    "titulo" : "Calculo" ,
    "lenguaje" : "matematicas" ,
    "vistas" : 45676,
    "nivel" : "avanzado"
}

###

GET http://localhost:3000/api/cursos/matematicas/calculo

###

PUT http://localhost:3000/api/cursos/matematicas/3 HTTP/1.1
Content-Type: application/json

{
    "id": 3,
    "titulo" : "Calculo" ,
    "lenguaje" : "matematicas" ,
    "vistas" : 45676,
    "nivel" : "intermedio"
}

###

PATCH http://localhost:3000/api/cursos/matematicas/3 HTTP/1.1
Content-Type: application/json

{
    "titulo": "holaaa"
}

###

DELETE http://localhost:3000/api/cursos/matematicas/3

###

GET http://localhost:3000/api/cursos/programacion/python?ordenar=vistas

