
GET http://localhost:3000/api

###

GET http://localhost:3000/api/cursos/programacion

###

GET http://localhost:3000/api/cursos/programacion/python

###

GET http://localhost:3000/api/cursos/programacion/python/basico

###

GET http://localhost:3000/api/cursos/matematicas

###

GET http://localhost:3000/api/cursos/matematicas/calculo

###

GET http://localhost:3000/api/cursos