GET http://localhost:3000/api/users

###


GET http://localhost:3000/

###


GET http://localhost:3000/api/storage


###

POST http://localhost:3000/api/storage HTTP/1.1
Content-Type: multipart/form-data; boundary=Boundry

--Boundry
Content-Disposition: form-data; name="image"; filename="login.jpg"
Content-Type: image/jpg

< ./login.jpg
--Boundry--

###

GET http://localhost:3000/file-1709629888158.jpg

###

POST http://localhost:3000/api/tracks HTTP/1.1
Content-Type: application/json
api-key: Api-publica-123

{
    "dato": "AALOOOO",
    "name": "buenas",
    "album": "cuentame",
    "cover": "http://yyy.com",
    "artist": {
        "name": "joe",
        "nickname": "parecetrue",
        "nationality": "ES"
    },
    "duration": {
        "start":1,
        "end":2
    },
    "mediaId": "0444456789abcdef01234567"
  
}

###

POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "dato": "id",
    "name": "antonin",
    "age": "19",
    "email": "crypto@gmail.com",
    "password": "1234567",
    "role":"user"
  
}

###

GET http://localhost:3000/api/tracks

###

GET http://localhost:3000/api/tracks/buenas

### 

POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "name": "paula",
    "age": "20",
    "email": "paulam@gmail.com",
    "password": "12345678",
    "role":"user"
  
}

###

GET http://localhost:3000/api/users

###/(probar)

GET http://localhost:3000/api/users/paula

###

