GET http://localhost:3000/api/users

###


GET http://localhost:3000/

###


GET http://localhost:3000/api/storag


###

POST http://localhost:3000/api/storage HTTP/1.1
Content-Type: multipart/form-data; boundary=Boundry

--Boundry
Content-Disposition: form-data; name="image"; filename="login.jpg"
Content-Type: image/jpg

< ./login.jpg
--Boundry--

###

GET http://localhost:3000/file-1709629888158.jpg

###

POST http://localhost:3000/api/tracks HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWYwMTM3NmY3NTFjMGU0NTY0ZDhhZjIiLCJlbWFpbCI6InRlc3QxMEB0ZXN0LmNvbSIsImlhdCI6MTcxMDIzMjQ1MCwiZXhwIjoxNzEwMjM5NjUwfQ.cefpbQCqDZgOCl-3ArT9NmEm4TE7QAmaGK_mzS8f3fc

{
    "dato": "AALOOOO",
    "name": "buenas",
    "album": "cuentame",
    "cover": "http://yyy.com",
    "artist": {
        "name": "joe",
        "nickname": "parecetrue",
        "nationality": "ES"
    },
    "duration": {
        "start":1,
        "end":2
    },
    "mediaId": "0444456789abcdef01234567"
  
}

###

POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "dato": "id",
    "name": "antonin",
    "age": "19",
    "email": "crypto@gmail.com",
    "password": "1234567",
    "role":"user"
  
}

###

GET http://localhost:3000/api/tracks

###

GET http://localhost:3000/api/tracks/buenas

### 

DELETE http://localhost:3000/api/tracks/buenas

###

POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "name": "elena",
    "age": "20",
    "email": "elena@gmail.com",
    "password": "12345678",
    "role":"user"
  
}

###

GET http://localhost:3000/api/users

###

GET http://localhost:3000/api/users/paula

###

DELETE http://localhost:3000/api/users/elena

###

POST http://localhost:3000/api/auth/login HTTP/1.1

###

POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "name": "Menganito",
    "age": 20,
    "email": "test10@test.com",
    "password": "HolaMundo.01"
}

###

POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "test10@test.com",
    "password": "HolaMundo.01"
}

###

GET http://localhost:3000/api/tracks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWYwMTM3NmY3NTFjMGU0NTY0ZDhhZjIiLCJlbWFpbCI6InRlc3QxMEB0ZXN0LmNvbSIsImlhdCI6MTcxMDIzMjQ1MCwiZXhwIjoxNzEwMjM5NjUwfQ.cefpbQCqDZgOCl-3ArT9NmEm4TE7QAmaGK_mzS8f3fc

###

PUT http://localhost:3000/api/users/65e6de6120cc8144d0584861
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWYwMTM3NmY3NTFjMGU0NTY0ZDhhZjIiLCJlbWFpbCI6InRlc3QxMEB0ZXN0LmNvbSIsImlhdCI6MTcxMDIzMjQ1MCwiZXhwIjoxNzEwMjM5NjUwfQ.cefpbQCqDZgOCl-3ArT9NmEm4TE7QAmaGK_mzS8f3fc