GET http://localhost:3000/api/users

###


GET http://localhost:3000/

###


GET http://localhost:3000/api/storage


###

POST http://localhost:3000/api/storage HTTP/1.1
Content-Type: multipart/form-data; boundary=Boundry

--Boundry
Content-Disposition: form-data; name="image"; filename="img.jpg"
Content-Type: image/jpg

< ./img.jpg
--Boundry--

###

GET http://localhost:3000/file-1708690942122.jpg

###

POST http://localhost:3000/api/tracks HTTP/1.1
Content-Type: application/json
api-key: Api-publica-123

{
    "dato": "AALOOOO",
    "name": "buenas",
    "album": "cuentame",
    "cover": "http://yyy.com",
    "artist": {
        "name": "joe",
        "nickname": "parecetrue",
        "nationality": "ES"
    },
    "duration": {
        "start":1,
        "end":2
    },
    "mediaId": "0444456789abcdef01234567"
  
}

###

POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "dato": "id",
    "name": "antonin",
    "age": "19",
    "email": "crypto@gmail.com",
    "password": "1234567",
    "role":"user"
  
}

###

GET http://localhost:3000/api/tracks

###

GET http://localhost:3000/api/tracks/buenas