### POST DE UN COMERCIO CON UN USUARIO QUE ES ADMINISTRADOR

POST http://localhost:3000/api/admin/crearComercio HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjNiYjc5ZDUyZjYwNmQ3YThmMWE3ZmYiLCJlbWFpbCI6InVzdWFyaW8xQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxNTg5MTUzNywiZXhwIjoxNzE1ODk4NzM3fQ.rWMSIhBseN_g4CUnlu1n59IPPx4R204MbKtJxngGa8s

{
    "nombreComercio": "Comercio 2",
    "cifComercio": "123456789k",
    "direccionComercio": "Calle 2",
    "emailComercio": "comercio2@gmail.com",
    "passwordComercio": "12345678",
    "telefonoComercio": "911542879"
}

### MODIFICACION DE UN COMERCIO CON UN USUARIO QUE ES ADMINISTRADOR
PUT http://localhost:3000/api/admin/6646301747eeb5b12c34ef11 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjNiYjc5ZDUyZjYwNmQ3YThmMWE3ZmYiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTU4Njk5ODIsImV4cCI6MTcxNTg3NzE4Mn0.SDiqFb3W8Mq__bwhMiQsiBufjRBMyz8f0lt5warlIjo

{
    "nombreComercio": "Comercio2",
    "cifComercio": "123456972k",
    "direccionComercio": "Calle 2",
    "emailComercio": "comercio2@gmail.com",
    "passwordComercio": "12345678",
    "telefonoComercio": "911542879"
}

###

DELETE http://localhost:3000/api/admin/deleteComercio/663c018cb5ea59eb9b57e47f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjMwZDRmNDZlNjI1MmZjY2NmZjE1OTQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTQ5NDE4MTgsImV4cCI6MTcxNDk0OTAxOH0.NZqcfeGwM6nAwpbHjLTwAqCCMPy3KlnbG4TW2rOxV9A

