### POST DE UN COMERCIO CON UN USUARIO QUE ES ADMINISTRADOR

POST http://localhost:3000/api/admin/crearComercio HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjNiYjc5ZDUyZjYwNmQ3YThmMWE3ZmYiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTUyMDg1NTgsImV4cCI6MTcxNTIxNTc1OH0.B532LB7-dN2XS5G6G-FmY5czJ5I6WsQByprfqzWDND0

{
    "nombreComercio": "Comercio 1",
    "cifComercio": "12345678",
    "direccionComercio": "Calle 1",
    "emailComercio": "comercio1@gmail.com",
    "passwordComercio": "hola12345",
    "telefonoContacto": "611452480"
}

### MODIFICACION DE UN COMERCIO CON UN USUARIO QUE ES ADMINISTRADOR
PUT http://localhost:3000/api/admin/663c0cfd86da146514813301 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjNiYjc5ZDUyZjYwNmQ3YThmMWE3ZmYiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTUyMTE2NzUsImV4cCI6MTcxNTIxODg3NX0.H-Bw2Tj283yrmb05dIniTh9mA7mn6zyXFdZvic1nYZ0

{
    "nombreComercio": "Comercio 1",
    "cifComercio": "12345678",
    "direccionComercio": "Calle 1",
    "emailComercio": "comercio1@gmail.com",
    "passwordComercio": "hola12345",
    "telefonoContacto": "611452480"
    
}

###

DELETE http://localhost:3000/api/admin/deleteComercio/663c018cb5ea59eb9b57e47f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjMwZDRmNDZlNjI1MmZjY2NmZjE1OTQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTQ5NDE4MTgsImV4cCI6MTcxNDk0OTAxOH0.NZqcfeGwM6nAwpbHjLTwAqCCMPy3KlnbG4TW2rOxV9A

