GET http://localhost:3000/api/comercio

###

GET http://localhost:3000/api/comercio/662be0ecd9edda32d5fd957e

### POST DE UN COMERCIO CON UN USUARIO NORMAL, QUE NO ES ADMINISTRADOR
POST http://localhost:3000/api/comercio HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjJiODk0YzNkNTk3MTAxNDg3YmRiYWMiLCJyb2xlIjoidXN1YXJpb1JlZ2lzdHJhZG8iLCJpYXQiOjE3MTQxNTE2NDIsImV4cCI6MTcxNDE1ODg0Mn0.XHG0CJLU3fruqDbVeK2tNoTlqFiX6Bd1w-cOOXF344c

{
    "nombreComercio": "Comercio 1",
    "cifComercio": "12345678",
    "direccionComercio": "Calle 1",
    "emailComercio": "comercio1@gmail.com",
    "passwordComercio": "12345678",
    "telefonoContacto": "4123456789"
}

### POST DE UN COMERCIO CON UN USUARIO QUE ES ADMINISTRADOR

POST http://localhost:3000/api/admin/crearComercio HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjJiNzVmYjEzOGI4MTY2MWFhN2IyOGEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTQyMTc5MzcsImV4cCI6MTcxNDIyNTEzN30.BnVCxRmNI_GlZX3EQzpQM_CLcOerNoe-tO8D5RZH2sA

{
    "nombreComercio": "Comercio 1",
    "cifComercio": "12345678",
    "direccionComercio": "Calle 1",
    "emailComercio": "comercio1@gmail.com",
    "passwordComercio": "12345678",
    "telefonoContacto": "4123456789FG"
    
}

### HACER LOGIN EN LA PAGINA DE UN COMERCIO
POST http://localhost:3000/api/comercio/loginComercio HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjJjZTQ3ZDMwOTI0NjhmNzk4YzZlZjciLCJpYXQiOjE3MTQyMTgxMDksImV4cCI6MTcxNDIyNTMwOX0.0thBng7yImZTuKKKpaezLSdkrTQQmY23n_7U_DQHj7E

{
    "emailComercio": "comercio1@gmail.com",
    "passwordComercio": "12345678"
}


### MODIFICACION DE UN COMERCIO CON UN USUARIO QUE NO ES ADMINISTRADOR
PUT http://localhost:3000/api/comercio/662b8acd7289b86a735ba4fb HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjJiODk0YzNkNTk3MTAxNDg3YmRiYWMiLCJyb2xlIjoidXN1YXJpb1JlZ2lzdHJhZG8iLCJpYXQiOjE3MTQxMzg1NzgsImV4cCI6MTcxNDE0NTc3OH0.J_SXDYqalW-HVad7zpc8zYj8GgUiWhkiSyTeAh3EQsc

{
    "nombreComercio": "Comercio1",
    "cifComercio": "12345678",
    "direccionComercio": "Calle1",
    "emailComercio": "comercio1@gmail.com",
    "passwordComercio":"12345678",
    "telefonoContacto": "4123456789",
    
}

### MODIFICACION DE UN COMERCIO CON UN USUARIO QUE ES ADMINISTRADOR
PUT http://localhost:3000/api/comercio/662b8acd7289b86a735ba4fb HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjJiNzVmYjEzOGI4MTY2MWFhN2IyOGEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTQyMTY0MTMsImV4cCI6MTcxNDIyMzYxM30.VcpoDhqcM7WooxCdOx64GC_tJRIRUk1Bn-IESTRSvus

{
    "nombreComercio": "Comercio1",
    "cifComercio": "12345678",
    "direccionComercio": "Calle1",
    "emailComercio": "comercio1@gmail.com",
    "telefonoContacto": "4123456789",
    
}


###

DELETE http://localhost:3000/api/comercio/662ce47d3092468f798c6ef7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjJjZTQ3ZDMwOTI0NjhmNzk4YzZlZjciLCJpYXQiOjE3MTQyMTgxMDksImV4cCI6MTcxNDIyNTMwOX0.0thBng7yImZTuKKKpaezLSdkrTQQmY23n_7U_DQHj7E

###
