GET http://localhost:3000/api/comercio
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjNiYjc5ZDUyZjYwNmQ3YThmMWE3ZmYiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTU4Njk5ODIsImV4cCI6MTcxNTg3NzE4Mn0.SDiqFb3W8Mq__bwhMiQsiBufjRBMyz8f0lt5warlIjo 

### GET de los Comercios; va a mostrar las paginas pertenecientes a los comercios
GET http://localhost:3000/api/comercio

### GET de un Comercio en especifico

GET http://localhost:3000/api/comercio/664619613521392f4d7b660d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjNiYjc5ZDUyZjYwNmQ3YThmMWE3ZmYiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTU4Njk5ODIsImV4cCI6MTcxNTg3NzE4Mn0.SDiqFb3W8Mq__bwhMiQsiBufjRBMyz8f0lt5warlIjo 

### POST DE UN COMERCIO CON UN USUARIO NORMAL, QUE NO ES ADMINISTRADOR
POST http://localhost:3000/api/comercio HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjNiYjc5ZDUyZjYwNmQ3YThmMWE3ZmYiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTU4Njk5ODIsImV4cCI6MTcxNTg3NzE4Mn0.SDiqFb3W8Mq__bwhMiQsiBufjRBMyz8f0lt5warlIjo

{
    "nombreComercio": "Comercio 1",
    "cifComercio": "12345678",
    "direccionComercio": "Calle 1",
    "emailComercio": "comercio1@gmail.com",
    "passwordComercio": "12345678",
    "telefonoComercio": "4123456789"
}



### HACER LOGIN EN LA PAGINA DE UN COMERCIO
POST http://localhost:3000/api/comercio/loginComercio HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjQ2MTk2MTM1MjEzOTJmNGQ3YjY2MGQiLCJpYXQiOjE3MTU4NzAwNDksImV4cCI6MTcxNTg3NzI0OX0.yOZ-WaPi1f4hHStSyRHKIfufggYp591DsjjQOcShGWs

{
    "emailComercio": "com@gmail.com",
    "passwordComercio": "hola12345"
}


