GET http://localhost:3000/api/paginaComercio

### VER LAS PAGINAS DE COMERCIO ORDENADAS POR PUNTUACION

GET http://localhost:3000/api/paginaComercio?scoring=true

### VER LOS COMERCIOS DE SU CIUDAD
GET http://localhost:3000/api/paginaComercio/search/Madrid

### VER TODAS LAS PAGINAS DE COMERCIOS DE UNA CIUDAD Y ACTIVIDAD

GET http://localhost:3000/api/paginaComercio/search/Barcelona/Actividad1


### VER UNA PAGINA DE COMERCIO

GET http://localhost:3000/api/paginaComercio/663d4c090ecb27ba0e77a7b6


### CREACION DE UNA PAGINA DE COMERCIO
POST http://localhost:3000/api/paginaComercio/createPage HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjNkNGJlODBlY2IyN2JhMGU3N2E3YjMiLCJpYXQiOjE3MTUyOTMxNjAsImV4cCI6MTcxNTMwMDM2MH0._9K4qZD8otUI3A8qormU3vAY5-Mfm6ZNG2OX8362Hy8

{
    "titulo": "Titulo 3",
    "ciudadComercio": "Madrid",
    "actividadComercio": "Actividad3",
    "resumenComercio": "Resumen 3"
}

### SUBIR UN TEXTO A LA PAGINA DE COMERCIO

POST http://localhost:3000/api/paginaComercio/textos/663d5f6392318e95a5db6ec2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjNkNGJlODBlY2IyN2JhMGU3N2E3YjMiLCJpYXQiOjE3MTUyOTMxNjAsImV4cCI6MTcxNTMwMDM2MH0._9K4qZD8otUI3A8qormU3vAY5-Mfm6ZNG2OX8362Hy8

{
    "textos": [
        "Texto 2",
        "Texto 3"
    ]
}


### MODIFICACION DE UN COMERCIO SIENDO EL COMERCIO PROPIO, solo puede modificar cosas de su pagina de comercio

PUT http://localhost:3000/api/paginaComercio/663d4c090ecb27ba0e77a7b6 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjNkNGJlODBlY2IyN2JhMGU3N2E3YjMiLCJpYXQiOjE3MTUyOTMxNjAsImV4cCI6MTcxNTMwMDM2MH0._9K4qZD8otUI3A8qormU3vAY5-Mfm6ZNG2OX8362Hy8

{
    "titulo": "Titulo3",
    "ciudadComercio": "Madrid",
    "actividadComercio": "Actividad 1",
    "resumenComercio": "Resumen 1"
}

### PATCH DE UNA PAGINA DE COMERCIO
PATCH http://localhost:3000/api/paginaComercio/663d5f6392318e95a5db6ec2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjNkNGJlODBlY2IyN2JhMGU3N2E3YjMiLCJpYXQiOjE3MTUyOTMxNjAsImV4cCI6MTcxNTMwMDM2MH0._9K4qZD8otUI3A8qormU3vAY5-Mfm6ZNG2OX8362Hy8

{
    "puntuacion": 10,
    "comentario": "Comentario 1"
}

### SUBIR UNA FOTO
POST http://localhost:3000/api/storage/photos/663a189881c35c818b836671 HTTP/1.1
Content-Type: multipart/form-data; boundary=Boundry
Authorization: BearereyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjNkNGJlODBlY2IyN2JhMGU3N2E3YjMiLCJpYXQiOjE3MTUyOTMxNjAsImV4cCI6MTcxNTMwMDM2MH0._9K4qZD8otUI3A8qormU3vAY5-Mfm6ZNG2OX8362Hy8

--Boundry
Content-Disposition: form-data; name="image"; filename="firmaSinFondo.png"
Content-Type: image/jpg

< ./firmaSinFondo.png
--Boundry--

### SUBIR OTRA FOTO
POST http://localhost:3000/api/storage/photos/663a189881c35c818b836671 HTTP/1.1
Content-Type: multipart/form-data; boundary=Boundry
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjNkNGJlODBlY2IyN2JhMGU3N2E3YjMiLCJpYXQiOjE3MTUyOTMxNjAsImV4cCI6MTcxNTMwMDM2MH0._9K4qZD8otUI3A8qormU3vAY5-Mfm6ZNG2OX8362Hy8

--Boundry
Content-Disposition: form-data; name="image"; filename="otra.png"
Content-Type: image/jpg

< ./otra.png
--Boundry--

### VER FOTOS DE UNA PAGINA DE COMERCIO
GET http://localhost:3000/api/storage/photos

### VER FOTO DE UNA PAGINA DE COMERCIO
GET http://localhost:3000/api/storage/photos/663e1384d6875feb34310a72

### ELIMINACION DE UNA PAGINA DE COMERCIO
DELETE http://localhost:3000/api/paginaComercio/6639fccf77905ea5d38f5f52 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjNkNGJlODBlY2IyN2JhMGU3N2E3YjMiLCJpYXQiOjE3MTUyOTMxNjAsImV4cCI6MTcxNTMwMDM2MH0._9K4qZD8otUI3A8qormU3vAY5-Mfm6ZNG2OX8362Hy8
