GET http://localhost:3000/api/paginaComercio

### VER LAS PAGINAS DE COMERCIO ORDENADAS POR PUNTUACION

GET http://localhost:3000/api/paginaComercio?scoring=true

### VER LOS COMERCIOS DE SU CIUDAD
GET http://localhost:3000/api/paginaComercio/search/Barcelona

### VER TODAS LAS PAGINAS DE COMERCIOS DE UNA CIUDAD Y ACTIVIDAD

GET http://localhost:3000/api/paginaComercio/search/Barcelona/Actividad1


### VER UNA PAGINA DE COMERCIO

GET http://localhost:3000/api/paginaComercio/664672bf218c7afc34bb2427


### CREACION DE UNA PAGINA DE COMERCIO
POST http://localhost:3000/api/paginaComercio/createPage HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjQ2NmUxZmI2MzI4NjM0YWNhNGY3NDkiLCJlbWFpbCI6ImNvbWVyY2lvMkBnbWFpbC5jb20iLCJpYXQiOjE3MTU4OTM4NjQsImV4cCI6MTcxNTkwMTA2NH0.vrl8CDwDgRZ5xba7xtu-kRCX8U0AjWftGNQKq21eG6M

{
    "titulo": "Titulo 2",
    "ciudadComercio": "Barcelona",
    "actividadComercio": "Actividad 2",
    "resumenComercio": "Resumen 2"
}

### SUBIR UN TEXTO A LA PAGINA DE COMERCIO

POST http://localhost:3000/api/paginaComercio/textos/66464dc3f3abeab31e1fb63e HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjQ2NGI4ZTY3NjQ2ZDRkNzUyYWQ3MmUiLCJlbWFpbCI6ImNvbWVyY2lvMUBnbWFpbC5jb20iLCJpYXQiOjE3MTU4ODI4OTQsImV4cCI6MTcxNTg5MDA5NH0.-395GQaSIsLm-Owadx5AdEld3Si82lYumVS2iv37rqQ

{
    "textos": [
        "Texto 1",
        "Texto 2"
    ]
}


### MODIFICACION DE UN COMERCIO SIENDO EL COMERCIO PROPIO, solo puede modificar cosas de su pagina de comercio

PUT http://localhost:3000/api/paginaComercio/664676b04eeefbb35585409d HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjQ2NmUxZmI2MzI4NjM0YWNhNGY3NDkiLCJlbWFpbCI6ImNvbWVyY2lvMkBnbWFpbC5jb20iLCJpYXQiOjE3MTU4OTM4NjQsImV4cCI6MTcxNTkwMTA2NH0.vrl8CDwDgRZ5xba7xtu-kRCX8U0AjWftGNQKq21eG6M

{
    "titulo": "Titulo 1",
    "ciudadComercio": "Barcelona",
    "actividadComercio": "Actividad 1",
    "resumenComercio": "Resumen 1"
}

### PATCH DE UNA PAGINA DE COMERCIO
PATCH http://localhost:3000/api/paginaComercio/664681581913de71873af4d5 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjQ2NmUxZmI2MzI4NjM0YWNhNGY3NDkiLCJlbWFpbCI6ImNvbWVyY2lvMkBnbWFpbC5jb20iLCJpYXQiOjE3MTU4OTM4NjQsImV4cCI6MTcxNTkwMTA2NH0.vrl8CDwDgRZ5xba7xtu-kRCX8U0AjWftGNQKq21eG6M

{
    "puntuacion": 5,
    "comentario": "Comentario 1"
}

### SUBIR UNA FOTO
POST http://localhost:3000/api/storage/photos/66464dc3f3abeab31e1fb63e HTTP/1.1
Content-Type: multipart/form-data; boundary=Boundry
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjQ2NmUxZmI2MzI4NjM0YWNhNGY3NDkiLCJlbWFpbCI6ImNvbWVyY2lvMkBnbWFpbC5jb20iLCJpYXQiOjE3MTU4OTE3NDMsImV4cCI6MTcxNTg5ODk0M30.r1CW7j1A_NHBH_CxRXnDOkXOrmym2uo-j6PeDEbHq5c

--Boundry
Content-Disposition: form-data; name="image"; filename="firmaSinFondo.png"
Content-Type: image/jpg

< ./firmaSinFondo.png
--Boundry--

### SUBIR OTRA FOTO
POST http://localhost:3000/api/storage/photos/664320c2b2dff40fa8b52c77 HTTP/1.1
Content-Type: multipart/form-data; boundary=Boundry
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjQzMWZiZWIyZGZmNDBmYThiNTJjNzQiLCJpYXQiOjE3MTU2NzUwNzAsImV4cCI6MTcxNTY4MjI3MH0.bZfmyfxtPFS2Cypd-nyuPKvLALqjmwBAJYL6k4yMf1o

--Boundry
Content-Disposition: form-data; name="image"; filename="otra.png"
Content-Type: image/jpg

< ./otra.png
--Boundry--

### VER FOTOS DE UNA PAGINA DE COMERCIO
GET http://localhost:3000/api/storage/photos

### VER FOTO DE UNA PAGINA DE COMERCIO
GET http://localhost:3000/api/storage/photos/663e1384d6875feb34310a72

### ELIMINACION DE UNA PAGINA DE COMERCIO
DELETE http://localhost:3000/api/paginaComercio/664681211913de71873af4c5 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjQ2NmUxZmI2MzI4NjM0YWNhNGY3NDkiLCJlbWFpbCI6ImNvbWVyY2lvMkBnbWFpbC5jb20iLCJpYXQiOjE3MTU4OTM4NjQsImV4cCI6MTcxNTkwMTA2NH0.vrl8CDwDgRZ5xba7xtu-kRCX8U0AjWftGNQKq21eG6M
