GET http://localhost:3000/api/paginaComercio

###

GET http://localhost:3000/api/paginaComercio/6630e91a321016a4d452b785


### CREACION DE UNA PAGINA DE COMERCIO
POST http://localhost:3000/api/paginaComercio/createPage HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjMxMGYxZWU4Mjc1OGUzOWVmMDUzYzMiLCJpYXQiOjE3MTQ0OTExNjYsImV4cCI6MTcxNDQ5ODM2Nn0.V2Kz9RA1HrlCIjxyRFTkqZDxrSlrPl0gvlI0-jGCKcs

{
    "titulo": "Titulo 1",
    "ciudadComercio": "Ciudad 1",
    "actividadComercio": "Actividad 1",
    "resumenComercio": "Resumen 1",
    "textos": [
        "Titulo 1: Descripcion 1"
    ],
    "fotos": [
        "https://www.google.com"
    ]
}


### MODIFICACION DE UN COMERCIO SIENDO EL COMERCIO PROPIO, solo puede modificar cosas de su pagina de comercio

PUT http://localhost:3000/api/paginaComercio/662b8acd7289b86a735ba4fb HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjJiYjAwNjJmNjkyZjA1OTYxZWY5MGIiLCJlbWFpbCI6ImNvbWVyY2lvMUBnbWFpbC5jb20iLCJpYXQiOjE3MTQxMzkxNDIsImV4cCI6MTcxNDE0NjM0Mn0.qfzAGdEA87vdb_dxJ14pOby0kykfwYJmBkr-icyZi2o

{
    "ciudadComercio": "Ciudad 1",
    "actividadComercio": "Actividad 1",
    "textos": [
        "Titulo 1: Descripcion 1"
    ],
    "fotos": [
        "https://www.google.com"
    ]
}

### ELIMINACION DE UNA PAGINA DE COMERCIO
DELETE http://localhost:3000/api/paginaComercio/66310f52e82758e39ef053c6 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjMxMGYxZWU4Mjc1OGUzOWVmMDUzYzMiLCJpYXQiOjE3MTQ0OTExNjYsImV4cCI6MTcxNDQ5ODM2Nn0.V2Kz9RA1HrlCIjxyRFTkqZDxrSlrPl0gvlI0-jGCKcs