GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "nombreUsuario": "Usuario 1",
    "emailUsuario": "usuario1@gmail.com",
    "passwordUsuario": "123456780",
    "edadUsuario": 22,
    "ciudadUsuario": "Ciudad 1",
    "interesesUsuario": [
        "Interes 1"
    ],
    "permiteOfertas": true
}

###

POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "emailUsuario": "usuario1@gmail.com",
    "passwordUsuario": "123456780"
}

###

GET http://localhost:3000/api/users/662ad81bdbd44d55b9b432ee

###

PUT http://localhost:3000/api/users/662ad81bdbd44d55b9b432ee HTTP/1.1
Content-Type: application/json

{
    "nombreUsuario": "Usuario 3",
    "emailUsuario": "usuario1@gmail.com",
    "passwordUsuario": "123456780",
    "edadUsuario": 22,
    "ciudadUsuario": "Ciudad 1",
    "interesesUsuario": [
        "Interes 1"
    ],
    "permiteOfertas": true
}

###

DELETE http://localhost:3000/api/users/662ac4fed396b807491c3ca5