GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "nombreUsuario": "Usuario 1",
    "emailUsuario": "usuario1@gmail.com",
    "passwordUsuario": "12345678",
    "edadUsuario": 22,
    "sexoUsuario": "Hombre",
    "ciudadUsuario": "Madrid",
    "interesesUsuario": [
        "Interes 1"
    ],
    "permiteOfertas": true
}

### USUARIO NO ADMIN
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "emailUsuario": "usuario1@gmail.com",
    "passwordUsuario": "1234578P"
}

### USUARIO ADMIN

POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "emailUsuario": "usuario3@gmail.com",
    "passwordUsuario": "1234578P"
}

### GET USUARIO POR ID

GET http://localhost:3000/api/users/6630d4f46e6252fcccff1594

### GET USUARIO POR CIUDAD

GET http://localhost:3000/api/users/user/Madrid


###

PUT http://localhost:3000/api/users/6630d4f46e6252fcccff1594 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjMwZDRmNDZlNjI1MmZjY2NmZjE1OTQiLCJyb2xlIjoidXN1YXJpb1JlZ2lzdHJhZG8iLCJpYXQiOjE3MTQ0NzYyNzYsImV4cCI6MTcxNDQ4MzQ3Nn0.Gnc4i90h1p1fxRINlFMsM01C9QKjU0SymCfIs1l6_ng

{
    "nombreUsuario": "Usuario 1",
    "emailUsuario": "usuario2@gmail.com",
    "passwordUsuario": "1234578P",
    "edadUsuario": 22,
    "sexoUsuario": "Hombre",
    "ciudadUsuario": "Ciudad 1",
    "interesesUsuario": [
        "Interes 1"
    ],
    "permiteOfertas": true
}

### DARSE DE BAJA A SI MISMO

DELETE http://localhost:3000/api/users/6630d4f46e6252fcccff1594
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjMwZDRmNDZlNjI1MmZjY2NmZjE1OTQiLCJyb2xlIjoidXN1YXJpb1JlZ2lzdHJhZG8iLCJpYXQiOjE3MTQ0NzYyNzYsImV4cCI6MTcxNDQ4MzQ3Nn0.Gnc4i90h1p1fxRINlFMsM01C9QKjU0SymCfIs1l6_ng

### PATCH DE UNA PAGINA DE COMERCIO
PATCH http://localhost:3000/api/paginaComercio/663b7c60212c6434766f34c3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjNiN2M0MzIxMmM2NDM0NzY2ZjM0YmQiLCJpYXQiOjE3MTUxNzQ0NjcsImV4cCI6MTcxNTE4MTY2N30.wyUTh2QLYTaoOkpImZxK3jVnXdmsZM3ikKdxoCiihz8

{
    "puntuacion": 10,
    "comentario": "Comentario 1"
}