GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "nombreUsuario": "Usuario 1",
    "emailUsuario": "usuario1@gmail.com",
    "passwordUsuario": "123456780",
    "edadUsuario": 22,
    "ciudadUsuario": "Ciudad 1",
    "interesesUsuario": [
        "Interes 1"
    ],
    "permiteOfertas": true
}

###

GET http://localhost:3000/api/users/662ab4dbd4ad6b2d4387968b

###

PUT http://localhost:3000/api/users/6629619413e13dd2ea7ae702 HTTP/1.1
Content-Type: application/json

{
    "nombreUsuario": "Usuario 3",
    "emailUsuario": "user3@gmail.com",
    "passwordUsuario": "123456",
    "edadUsuario": 22,
    "ciudadUsuario": "Ciudad 3",
    "interesesUsuario": [
        "Interes 3"
    ],
    "permiteOfertas": false,
    "role": "admin"
}

###

DELETE http://localhost:3000/api/users/662ab4dbd4ad6b2d4387968b