import './globals.css'

export const metadata = {
  title: 'WEB PRACTICA',
  description: 'Generated by PAULA MENDEZ',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">

            <body>
                {children}
            </body>

        </html>
    )
}
